server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courselearning?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 200MB #设置上传文件大小不得超过200MB
      max-request-size: 210MB #设置一次请求的数据量不得超过200MB
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/

# 设置日志输出
logging:
  level:
    #cn.seecoder.courselearning.mapperservice: DEBUG
    cn.seecoder.courselearning.service: DEBUG
#  file:
#    path: D:/courselearning/


# 自定义标签 ${web.file-upload-path} 用于存储向服务器上传的文件
web:
  file-upload-path: /app/
#web:
#  file-upload-path: D:/courselearning/upload/

